#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Time
from rosgraph_msgs.msg import Clock


class ClockPublisher(Node):
    def __init__(self):
        super().__init__('clock_publisher')
        self.clock_pub = self.create_publisher(Clock, '/clock', 10)
        self.timer = self.create_timer(0.05, self.publish_time)
        self.sim_time = 0.0
        self.time_increment = 0.05

    def publish_time(self):
        self.sim_time += self.time_increment
        clock_msg = Clock()
        clock_msg.clock = Time()
        clock_msg.clock.sec = int(self.sim_time)
        clock_msg.clock.nanosec = int((self.sim_time - int(self.sim_time)) * 1e9)
        self.clock_pub.publish(clock_msg)


def main(args=None):
    rclpy.init(args=args)
    node = ClockPublisher()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
