uavs:
  - id: 0
    spawn_pose: [3.0, 0.0, 0.2, 0.0, 0.0, 1.57079632679]
    offboard:
      trajectory_csv_file: trajectory_lemniscate_uav.csv
      lookahead_distance: 2.0
      cruise_speed: 0.5
      odom_error_position: 0.0
      odom_error_angle: 0.0
    tags:
      - id: 1
        position: [-0.24, -0.24, -0.06]
      - id: 2
        position: [0.24, 0.24, -0.06]

ugvs:
  - id: 0
    spawn_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.57079632679]
    offboard:
      trajectory_csv_file: trajectory_lemniscate_agv.csv
      lookahead_distance: 2.0
      cruise_speed: 0.52
      odom_error_position: 0.0
      odom_error_angle: 0.0
    anchors:
      - id: 1
        position: [-0.32, 0.3, 0.875]
      - id: 2
        position: [0.32, -0.3, 0.875]
      - id: 3
        position: [0.32, 0.3, 0.33]
      - id: 4
        position: [-0.32, -0.3, 0.33]
