uavs:
  - id: 0
    spawn_pose: [3.0, 0.0, 0.0, 0.0, 0.0, 1.57079632679]
    tags:
      - id: 1
        position: [-0.24, -0.24, -0.06]
      - id: 2
        position: [0.24, 0.24, -0.06]

  - id: 1
    spawn_pose: [3.0, -5.0, 0.0, 0.0, 0.0, 1.57079632679]
    tags:
      - id: 3
        position: [-0.24, -0.24, -0.06]
      - id: 4
        position: [0.24, 0.24, -0.06]

ugvs:
  - id: 0
    spawn_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.57079632679]
    anchors:
      - id: 1
        position: [-0.32, 0.3, 0.875]
      - id: 2
        position: [0.32, -0.3, 0.875]
      - id: 3
        position: [0.32, 0.3, 0.33]
      - id: 4
        position: [-0.32, -0.3, 0.33]

  - id: 1
    spawn_pose: [0.0, -5.0, 0.0, 0.0, 0.0, 1.57079632679]
    anchors:
      - id: 5
        position: [-0.32, 0.3, 0.875]
      - id: 6
        position: [0.32, -0.3, 0.875]
      - id: 7
        position: [0.32, 0.3, 0.33]
      - id: 8
        position: [-0.32, -0.3, 0.33]
