agv_offboard_control:
  ros__parameters:
    offboard_control_mode_topic: "/px4_2/fmu/in/offboard_control_mode"
    trajectory_setpoint_topic: "/px4_2/fmu/in/trajectory_setpoint"
    vehicle_command_topic: "/px4_2/fmu/in/vehicle_command"
    vehicle_odometry_topic: "/px4_2/fmu/out/vehicle_odometry"
    vehicle_local_position_topic: "/px4_2/fmu/out/vehicle_local_position_v1"
    trajectory_csv_file: "trajectory_lemniscate_agv.csv"
    ros_odometry_topic: "/agv/odom"
    ros_gt_topic: "/agv/gt"
    lookahead_distance: 2.0
    cruise_speed: 0.52
    odom_error_position: 2.0 # %,  meters for every 100 meters traveled
    odom_error_angle: 2.0 # % degrees for every 100 degrees
    agv_origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] #x y z r p y #spawning location of the AGV in Gazebo(ENU)
    anchors:
      ids: ["0x0009D6", "0x0009E5", "0x0016FA", "0x0016CF"]
    tags:
      ids: ["0x001155", "0x001397"]
